using System.Xml.Linq;
using iDeal.Base;

namespace iDeal.Transaction
{
    public class TransactionResponse : iDealResponse
    {
        /// <summary>
        /// Url of issuer to which the customer has to be redirected
        /// </summary>
        public string IssuerAuthenticationUrl { get; private set; }

        /// <summary>
        /// Acquirer id (first four digits) + unique id generated by acquirer (last 12 digits)
        /// </summary>
        public string TransactionId { get; private set; }

        /// <summary>
        /// Unique id determined by the acceptant, which will eventuelly show on the bank account
        /// </summary>
        public string PurchaseId { get; private set; }

        public TransactionResponse(string xmlDirectoryResponse)
        {
            // Parse document
            XElement xDocument = XElement.Parse(xmlDirectoryResponse);

            // Create datetimestamp
            CreateDateTimestamp = xDocument.Element(Xml.Ns + "createDateTimestamp").Value;

            // Acquirer id
            AcquirerId = (int) xDocument.Element(Xml.Ns + "Acquirer").Element(Xml.Ns + "acquirerID");

            // IssuerAuthenticationUrl
            IssuerAuthenticationUrl =
                xDocument.Element(Xml.Ns + "Issuer").Element(Xml.Ns + "issuerAuthenticationURL").Value;

            // TransactionId
            TransactionId = xDocument.Element(Xml.Ns + "Transaction").Element(Xml.Ns + "transactionID").Value;

            // PurchaseId
            PurchaseId = xDocument.Element(Xml.Ns + "Transaction").Element(Xml.Ns + "purchaseID").Value;
        }
    }
}